USE SUCOS_VENDAS;

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME FROM TABELA_DE_CLIENTES;

SELECT CPF AS INDENTIFICADOR, NOME AS CLIENTE FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA';

########## CONDIÇÕES lÓGICAS ###############

SELECT * FROM tabela_de_produtos WHERE SABOR = 'manga' OR TAMANHO = '470 ml';

SELECT * FROM tabela_de_produtos WHERE SABOR = 'manga' AND TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT ( SABOR = 'LARANJA' AND TAMANHO > '300 ML');

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT ( SABOR = 'LARANJA' OR TAMANHO > '300 ML');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('LARANJA', 'MANGA');

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('RIO DE JANEIRO','SAO PAULO')AND  IDADE >= 20;

########## COMANDO LIKE ###############

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%MAÇA%'; 

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%MAÇA%' AND EMBALAGEM = 'PET';


