
############ COMANDO DISTINCT ###############
SELECT  EMBALAGEM, TAMANHO FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM TABELA_DE_PRODUTOS WHERE SABOR = 'LARANJA'; # 

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM TABELA_DE_PRODUTOS;

############ COMANDO LIMIT #######################

SELECT * FROM TABELA_DE_PRODUTOS LIMIT 0,2;

############## COMANDO ORDER BY ###################

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY TAMANHO DESC;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY embalagem DESC, nome_do_produto	ASC;

##### COMANDO GROUP BY ##################

SELECT ESTADO, LIMITE_DE_CREDITO FROM TABELA_DE_CLIENTES;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

SELECT EMBALAGEM, COUNT(*) AS CONTADOR FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

########### HAVING #############

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM TABELA_DE_CLIENTES GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA)  AS MENOR_PRECO FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80;

############ CASE #################

SELECT * FROM TABELA_DE_PRODUTOS;


SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
CASE 
	WHEN PRECO_DE_LISTA <= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >=7 AND PRECO_DE_LISTA <12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'
END AS STATUS_PRECO 
FROM tabela_de_produtos;


SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >=7 AND PRECO_DE_LISTA <12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'
END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO 
FROM tabela_de_produtos
GROUP BY EMBALAGEM,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >=7 AND PRECO_DE_LISTA <12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'
END;
	
